In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


In [2]:
dataset=pd.read_csv("CKD.csv")
dataset

age         bp sg   al   su     rbc        pc         pcc  \
0     2.000000  76.459948  c  3.0  0.0  normal  abnormal  notpresent   
1     3.000000  76.459948  c  2.0  0.0  normal    normal  notpresent   
2     4.000000  76.459948  a  1.0  0.0  normal    normal  notpresent   
3     5.000000  76.459948  d  1.0  0.0  normal    normal  notpresent   
4     5.000000  50.000000  c  0.0  0.0  normal    normal  notpresent   
..         ...        ... ..  ...  ...     ...       ...         ...   
394  51.492308  70.000000  a  0.0  0.0  normal    normal  notpresent   
395  51.492308  70.000000  c  0.0  2.0  normal    normal  notpresent   
396  51.492308  70.000000  c  3.0  0.0  normal    normal  notpresent   
397  51.492308  90.000000  a  0.0  0.0  normal    normal  notpresent   
398  51.492308  80.000000  a  0.0  0.0  normal    normal  notpresent   

             ba         bgr  ...        pcv            wc        rc  htn   dm  \
0    notpresent  148.112676  ...  38.868902   8408.191126  4.705597   no   no   
1    notpresent  148.112676  ...  34.000000  12300.000000  4.705597   no   no   
2    notpresent   99.000000  ...  34.000000   8408.191126  4.705597   no   no   
3    notpresent  148.112676  ...  38.868902   8408.191126  4.705597   no   no   
4    notpresent  148.112676  ...  36.000000  12400.000000  4.705597   no   no   
..          ...         ...  ...        ...           ...       ...  ...  ...   
394  notpresent  219.000000  ...  37.000000   9800.000000  4.400000   no   no   
395  notpresent  220.000000  ...  27.000000   8408.191126  4.705597  yes  yes   
396  notpresent  110.000000  ...  26.000000   9200.000000  3.400000  yes  yes   
397  notpresent  207.000000  ...  38.868902   8408.191126  4.705597  yes  yes   
398  notpresent  100.000000  ...  53.000000   8500.000000  4.900000   no   no   

     cad  appet    pe  ane classification  
0     no    yes   yes   no            yes  
1     no    yes  poor   no            yes  
2     no    yes  poor   no            yes  
3     no    yes  poor  yes            yes  
4     no    yes  poor   no            yes  
..   ...    ...   ...  ...            ...  
394   no    yes  poor   no            yes  
395   no    yes  poor  yes            yes  
396   no   poor  poor   no            yes  
397   no    yes  poor  yes            yes  
398   no    yes  poor   no             no  

[399 rows x 25 columns]

In [3]:
dataset=pd.get_dummies(dataset,drop_first=True)
dataset

age         bp   al   su         bgr          bu        sc  \
0     2.000000  76.459948  3.0  0.0  148.112676   57.482105  3.077356   
1     3.000000  76.459948  2.0  0.0  148.112676   22.000000  0.700000   
2     4.000000  76.459948  1.0  0.0   99.000000   23.000000  0.600000   
3     5.000000  76.459948  1.0  0.0  148.112676   16.000000  0.700000   
4     5.000000  50.000000  0.0  0.0  148.112676   25.000000  0.600000   
..         ...        ...  ...  ...         ...         ...       ...   
394  51.492308  70.000000  0.0  0.0  219.000000   36.000000  1.300000   
395  51.492308  70.000000  0.0  2.0  220.000000   68.000000  2.800000   
396  51.492308  70.000000  3.0  0.0  110.000000  115.000000  6.000000   
397  51.492308  90.000000  0.0  0.0  207.000000   80.000000  6.800000   
398  51.492308  80.000000  0.0  0.0  100.000000   49.000000  1.000000   

            sod       pot       hrmo  ...  pc_normal  pcc_present  ba_present  \
0    137.528754  4.627244  12.518156  ...          0            0           0   
1    137.528754  4.627244  10.700000  ...          1            0           0   
2    138.000000  4.400000  12.000000  ...          1            0           0   
3    138.000000  3.200000   8.100000  ...          1            0           0   
4    137.528754  4.627244  11.800000  ...          1            0           0   
..          ...       ...        ...  ...        ...          ...         ...   
394  139.000000  3.700000  12.500000  ...          1            0           0   
395  137.528754  4.627244   8.700000  ...          1            0           0   
396  134.000000  2.700000   9.100000  ...          1            0           0   
397  142.000000  5.500000   8.500000  ...          1            0           0   
398  140.000000  5.000000  16.300000  ...          1            0           0   

     htn_yes  dm_yes  cad_yes  appet_yes  pe_yes  ane_yes  classification_yes  
0          0       0        0          1       1        0                   1  
1          0       0        0          1       0        0                   1  
2          0       0        0          1       0        0                   1  
3          0       0        0          1       0        1                   1  
4          0       0        0          1       0        0                   1  
..       ...     ...      ...        ...     ...      ...                 ...  
394        0       0        0          1       0        0                   1  
395        1       1        0          1       0        1                   1  
396        1       1        0          0       0        0                   1  
397        1       1        0          1       0        1                   1  
398        0       0        0          1       0        0                   0  

[399 rows x 28 columns]

In [4]:
dataset.columns

Index(['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes', 'classification_yes'],
      dtype='object')

In [5]:
indep=dataset[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes']]
indep

age         bp   al   su         bgr          bu        sc  \
0     2.000000  76.459948  3.0  0.0  148.112676   57.482105  3.077356   
1     3.000000  76.459948  2.0  0.0  148.112676   22.000000  0.700000   
2     4.000000  76.459948  1.0  0.0   99.000000   23.000000  0.600000   
3     5.000000  76.459948  1.0  0.0  148.112676   16.000000  0.700000   
4     5.000000  50.000000  0.0  0.0  148.112676   25.000000  0.600000   
..         ...        ...  ...  ...         ...         ...       ...   
394  51.492308  70.000000  0.0  0.0  219.000000   36.000000  1.300000   
395  51.492308  70.000000  0.0  2.0  220.000000   68.000000  2.800000   
396  51.492308  70.000000  3.0  0.0  110.000000  115.000000  6.000000   
397  51.492308  90.000000  0.0  0.0  207.000000   80.000000  6.800000   
398  51.492308  80.000000  0.0  0.0  100.000000   49.000000  1.000000   

            sod       pot       hrmo  ...  rbc_normal  pc_normal  pcc_present  \
0    137.528754  4.627244  12.518156  ...           1          0            0   
1    137.528754  4.627244  10.700000  ...           1          1            0   
2    138.000000  4.400000  12.000000  ...           1          1            0   
3    138.000000  3.200000   8.100000  ...           1          1            0   
4    137.528754  4.627244  11.800000  ...           1          1            0   
..          ...       ...        ...  ...         ...        ...          ...   
394  139.000000  3.700000  12.500000  ...           1          1            0   
395  137.528754  4.627244   8.700000  ...           1          1            0   
396  134.000000  2.700000   9.100000  ...           1          1            0   
397  142.000000  5.500000   8.500000  ...           1          1            0   
398  140.000000  5.000000  16.300000  ...           1          1            0   

     ba_present  htn_yes  dm_yes  cad_yes  appet_yes  pe_yes  ane_yes  
0             0        0       0        0          1       1        0  
1             0        0       0        0          1       0        0  
2             0        0       0        0          1       0        0  
3             0        0       0        0          1       0        1  
4             0        0       0        0          1       0        0  
..          ...      ...     ...      ...        ...     ...      ...  
394           0        0       0        0          1       0        0  
395           0        1       1        0          1       0        1  
396           0        1       1        0          0       0        0  
397           0        1       1        0          1       0        1  
398           0        0       0        0          1       0        0  

[399 rows x 27 columns]

In [6]:
dep=dataset[['classification_yes']]
dep

classification_yes
0                     1
1                     1
2                     1
3                     1
4                     1
..                  ...
394                   1
395                   1
396                   1
397                   1
398                   0

[399 rows x 1 columns]

In [7]:
dataset["classification_yes"].value_counts()

1    249
0    150
Name: classification_yes, dtype: int64

In [8]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(indep,dep,test_size=1/3,random_state=0)
x_train,x_test,y_train,y_test


(      age     bp   al   su    bgr         bu        sc         sod       pot  \
 240  60.0  100.0  0.0  3.0  263.0  27.000000  1.300000  135.000000  4.300000   
 218  57.0   80.0  0.0  0.0  120.0  48.000000  1.600000  137.528754  4.627244   
 101  42.0   70.0  0.0  0.0   75.0  31.000000  1.200000  141.000000  3.500000   
 311  66.0   70.0  1.0  0.0  248.0  30.000000  1.700000  138.000000  5.300000   
 194  55.0   80.0  0.0  0.0  146.0  57.482105  3.077356  137.528754  4.627244   
 ..    ...    ...  ...  ...    ...        ...       ...         ...       ...   
 323  68.0   70.0  0.0  0.0   98.0  86.000000  4.600000  135.000000  3.400000   
 192  54.0   90.0  1.0  0.0  150.0  18.000000  1.200000  140.000000  4.200000   
 117  45.0   80.0  0.0  0.0  107.0  15.000000  1.000000  141.000000  4.200000   
 47   30.0   80.0  0.0  0.0   89.0  42.000000  0.500000  139.000000  5.000000   
 172  51.0   60.0  0.0  0.0  129.0  25.000000  1.200000  139.000000  5.000000   
 
           hrmo  ...  rbc_

In [9]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [10]:
x_train,x_test

(array([[ 0.48681432,  1.79924415, -0.68384276, ...,  0.51639778,
         -0.52223297, -0.44519456],
        [ 0.30305399,  0.26080096, -0.68384276, ...,  0.51639778,
         -0.52223297, -0.44519456],
        [-0.61574769, -0.50842064, -0.68384276, ...,  0.51639778,
         -0.52223297, -0.44519456],
        ...,
        [-0.43198735,  0.26080096, -0.68384276, ...,  0.51639778,
         -0.52223297, -0.44519456],
        [-1.35078903,  0.26080096, -0.68384276, ...,  0.51639778,
         -0.52223297, -0.44519456],
        [-0.06446668, -1.27764223, -0.68384276, ...,  0.51639778,
         -0.52223297, -0.44519456]]),
 array([[-0.37073391, -0.50842064, -0.68384276, ...,  0.51639778,
         -0.52223297, -0.44519456],
        [ 0.85433499,  1.03002255,  0.94028379, ..., -1.93649167,
         -0.52223297, -0.44519456],
        [ 1.03809533, -0.50842064, -0.68384276, ...,  0.51639778,
         -0.52223297, -0.44519456],
        ...,
        [-0.24822702,  1.79924415, -0.68384276, ..., -

In [11]:
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV
param_grid={'kernel':['linear','rbf','poly','sigmoid'],
           'gamma':['auto','scale'],
           'C':[10,100,1000,2000,3000]}
grid=GridSearchCV(SVC(probability=True),param_grid,refit=True,verbose=3,n_jobs=-1,scoring='f1_weighted')
grid.fit(x_train,y_train)

Fitting 5 folds for each of 40 candidates, totalling 200 fits


C:\Users\PC\Anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GridSearchCV(estimator=SVC(probability=True), n_jobs=-1,
             param_grid={'C': [10, 100, 1000, 2000, 3000],
                         'gamma': ['auto', 'scale'],
                         'kernel': ['linear', 'rbf', 'poly', 'sigmoid']},
             scoring='f1_weighted', verbose=3)

In [12]:
re=grid.cv_results_
grid_predictions=grid.predict(x_test)
grid_predictions


array([0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1,
       0], dtype=uint8)

In [13]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,grid_predictions)
print("Confusion Matrix:\n",cm)

Confusion Matrix:
 [[51  0]
 [ 1 81]]


In [14]:
from sklearn.metrics import classification_report
clf_report=classification_report(y_test,grid_predictions)
print("classification_report:\n",clf_report)

classification_report:
               precision    recall  f1-score   support

           0       0.98      1.00      0.99        51
           1       1.00      0.99      0.99        82

    accuracy                           0.99       133
   macro avg       0.99      0.99      0.99       133
weighted avg       0.99      0.99      0.99       133



In [15]:
from sklearn.metrics import f1_score
f1_macro=f1_score(y_test,grid_predictions,average='weighted')
print("The f1_macro value for best parameter{}:\n".format(grid.best_params_),f1_macro)

The f1_macro value for best parameter{'C': 10, 'gamma': 'auto', 'kernel': 'sigmoid'}:
 0.9924946382275899


In [25]:
from sklearn.metrics import roc_auc_score
ROC=roc_auc_score(y_test,grid.predict_proba(x_test)[:,1])
print("roc_auc_score=",ROC)

roc_auc_score= 1.0


In [17]:
table=pd.DataFrame.from_dict(re)
table

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_C  \
0        0.024994  1.874633e-02         0.000000        0.000000      10   
1        0.015087  1.069832e-03         0.006978        0.007182      10   
2        0.021870  7.653195e-03         0.003124        0.006249      10   
3        0.012496  6.247926e-03         0.006248        0.007652      10   
4        0.009373  7.652981e-03         0.006248        0.007653      10   
5        0.009374  7.653604e-03         0.006249        0.007654      10   
6        0.018744  6.248403e-03         0.000000        0.000000      10   
7        0.015622  2.336015e-07         0.000000        0.000000      10   
8        0.006248  7.652787e-03         0.000000        0.000000     100   
9        0.008021  4.994422e-03         0.006407        0.004914     100   
10       0.012546  6.069262e-04         0.002826        0.001021     100   
11       0.006685  1.005454e-03         0.002226        0.000388     100   
12       0.006210  1.292720e-03         0.001622        0.001176     100   
13       0.005145  5.918554e-03         0.000000        0.000000     100   
14       0.018746  6.248426e-03         0.000000        0.000000     100   
15       0.003124  6.248474e-03         0.009373        0.007653     100   
16       0.012498  6.248832e-03         0.000000        0.000000    1000   
17       0.012497  6.248522e-03         0.000000        0.000000    1000   
18       0.009372  7.652358e-03         0.006248        0.007653    1000   
19       0.009373  7.653059e-03         0.000000        0.000000    1000   
20       0.015622  9.879404e-03         0.000000        0.000000    1000   
21       0.009372  1.249682e-02         0.009378        0.007657    1000   
22       0.021870  7.651853e-03         0.000000        0.000000    1000   
23       0.015621  9.879856e-03         0.000000        0.000000    1000   
24       0.009378  7.657387e-03         0.003119        0.006237    2000   
25       0.012493  6.246578e-03         0.003124        0.006248    2000   
26       0.021868  7.654227e-03         0.000000        0.000000    2000   
27       0.015621  1.743947e-05         0.000000        0.000000    2000   
28       0.009373  7.652748e-03         0.000000        0.000000    2000   
29       0.015616  9.879108e-03         0.000000        0.000000    2000   
30       0.021870  7.652397e-03         0.000000        0.000000    2000   
31       0.009367  7.647926e-03         0.003125        0.006250    2000   
32       0.006248  7.652787e-03         0.003124        0.006249    3000   
33       0.015621  1.883356e-06         0.003124        0.006249    3000   
34       0.012497  6.248355e-03         0.006248        0.007653    3000   
35       0.009373  7.652670e-03         0.006249        0.007653    3000   
36       0.000000  0.000000e+00         0.012497        0.006248    3000   
37       0.009373  7.652826e-03         0.003124        0.006249    3000   
38       0.015621  5.761645e-07         0.003124        0.006249    3000   
39       0.012499  6.249500e-03         0.000000        0.000000    3000   

   param_gamma param_kernel  \
0         auto       linear   
1         auto          rbf   
2         auto         poly   
3         auto      sigmoid   
4        scale       linear   
5        scale          rbf   
6        scale         poly   
7        scale      sigmoid   
8         auto       linear   
9         auto          rbf   
10        auto         poly   
11        auto      sigmoid   
12       scale       linear   
13       scale          rbf   
14       scale         poly   
15       scale      sigmoid   
16        auto       linear   
17        auto          rbf   
18        auto         poly   
19        auto      sigmoid   
20       scale       linear   
21       scale          rbf   
22       scale         poly   
23       scale      sigmoid   
24        auto       linear   
25        auto          rbf   
26        auto         poly   
27        auto     

In [18]:
print(grid.best_params_)

{'C': 10, 'gamma': 'auto', 'kernel': 'sigmoid'}


In [20]:
age_input=float(input('Age:'))
bp_input=float(input('bp'))
al_input=float(input("al:"))
su_input=float(input("su:"))
bgr_input=float(input("bgr:"))
bu_input=float(input("bu:"))
sc_input=float(input("sc:"))
sod_input=float(input("sod:"))
pot_input=float(input("pot:"))
hrmo_input=float(input("hrmo:"))
pcv_input=int(input("pcv:"))
wc_input=int(input("wc:"))
rc_input=int(input("rc:"))
sg_b_input=int(input("sg_b:"))
sg_c_input=int(input("sg_c:"))
sg_d_input=int(input("sg_d:"))
sg_e_input=int(input("sg_e:"))
rbc_normal_input=int(input("rbc_normal:"))
pc_normal_input=int(input("pc_normal:"))
pcc_present_input=int(input("pcc_present:"))
ba_present_input=int(input("ba_present:"))
htn_yes_input=int(input("htn_yes:"))
dm_yes_input=int(input("dm_yes:"))
cad_yes_input=int(input("cad_yes:"))
appet_yes_input=int(input("appet_yes:"))
pe_yes_input=int(input("pe_yes:"))
ane_yes_input=int(input("ane_yes:"))

Age:52
bp72
al:0.00
su:0.20
bgr:220
bu:40
sc:2.5
sod:140
pot:3
hrmo:14
pcv:0
wc:0
rc:1
sg_b:0
sg_c:1
sg_d:0
sg_e:0
rbc_normal:1
pc_normal:1
pcc_present:0
ba_present:0
htn_yes:0
dm_yes:1
cad_yes:0
appet_yes:1
pe_yes:0
ane_yes:0


In [23]:
Future_prediction=grid.predict([[age_input,bp_input,al_input,su_input,bgr_input,bu_input,sc_input,sod_input,pot_input,hrmo_input,pcv_input,wc_input,rc_input,sg_b_input,sg_c_input,sg_d_input,sg_e_input,rbc_normal_input,pc_normal_input,pcc_present_input,ba_present_input,htn_yes_input,dm_yes_input,cad_yes_input,
       appet_yes_input,pe_yes_input,ane_yes_input]])
print("Future_Prediction={}".format(Future_prediction))

Future_Prediction=[1]
